var searchData=
[
  ['iaudioplayer',['IAudioPlayer',['../interface_xamarin_1_1_forms_1_1_core_1_1_i_audio_player.html',1,'Xamarin::Forms::Core']]],
  ['ibackgroundtimer',['IBackgroundTimer',['../interface_xamarin_1_1_forms_1_1_core_1_1_i_background_timer.html',1,'Xamarin::Forms::Core']]],
  ['ibluroverlay',['IBlurOverlay',['../interface_xamarin_1_1_forms_1_1_core_1_1_i_blur_overlay.html',1,'Xamarin::Forms::Core']]],
  ['icalendarevent',['ICalendarEvent',['../interface_xamarin_1_1_forms_1_1_core_1_1_i_calendar_event.html',1,'Xamarin::Forms::Core']]],
  ['icontextmenuservice',['IContextMenuService',['../interface_xamarin_1_1_forms_1_1_core_1_1_i_context_menu_service.html',1,'Xamarin::Forms::Core']]],
  ['idialogprompt',['IDialogPrompt',['../interface_xamarin_1_1_forms_1_1_core_1_1_i_dialog_prompt.html',1,'Xamarin::Forms::Core']]],
  ['iencryptionservice',['IEncryptionService',['../interface_xamarin_1_1_forms_1_1_core_1_1_i_encryption_service.html',1,'Xamarin::Forms::Core']]],
  ['ifilestore',['IFileStore',['../interface_xamarin_1_1_forms_1_1_core_1_1_i_file_store.html',1,'Xamarin::Forms::Core']]],
  ['ihttpservice',['IHttpService',['../interface_xamarin_1_1_forms_1_1_core_1_1_i_http_service.html',1,'Xamarin::Forms::Core']]],
  ['iintervalcallback',['IIntervalCallback',['../interface_xamarin_1_1_forms_1_1_core_1_1_i_interval_callback.html',1,'Xamarin::Forms::Core']]],
  ['ilocalnotify',['ILocalNotify',['../interface_xamarin_1_1_forms_1_1_core_1_1_i_local_notify.html',1,'Xamarin::Forms::Core']]],
  ['imapnavigate',['IMapNavigate',['../interface_xamarin_1_1_forms_1_1_core_1_1_i_map_navigate.html',1,'Xamarin::Forms::Core']]],
  ['installationid',['InstallationId',['../class_xamarin_1_1_forms_1_1_core_1_1_core_settings.html#a1855c51e5830cd2320ea8fc949a87e2a',1,'Xamarin::Forms::Core::CoreSettings']]],
  ['invertedbooleanconverter',['InvertedBooleanConverter',['../class_xamarin_1_1_forms_1_1_core_1_1_inverted_boolean_converter.html',1,'Xamarin::Forms::Core']]],
  ['ioverlaydependency',['IOverlayDependency',['../interface_xamarin_1_1_forms_1_1_core_1_1_i_overlay_dependency.html',1,'Xamarin::Forms::Core']]],
  ['ipopup',['IPopup',['../interface_xamarin_1_1_forms_1_1_core_1_1_i_popup.html',1,'Xamarin::Forms::Core']]],
  ['iprogressindicator',['IProgressIndicator',['../interface_xamarin_1_1_forms_1_1_core_1_1_i_progress_indicator.html',1,'Xamarin::Forms::Core']]],
  ['isearchprovider',['ISearchProvider',['../interface_xamarin_1_1_forms_1_1_core_1_1_i_search_provider.html',1,'Xamarin::Forms::Core']]],
  ['isecuredataservice',['ISecureDataService',['../interface_xamarin_1_1_forms_1_1_core_1_1_i_secure_data_service.html',1,'Xamarin::Forms::Core']]],
  ['isnackbar',['ISnackBar',['../interface_xamarin_1_1_forms_1_1_core_1_1_i_snack_bar.html',1,'Xamarin::Forms::Core']]],
  ['isregistered_3c_20t_20_3e',['IsRegistered&lt; T &gt;',['../class_xamarin_1_1_forms_1_1_core_1_1_core_dependency_service.html#a1c7c5701b607167e4f81fb2f91b443a7',1,'Xamarin::Forms::Core::CoreDependencyService']]],
  ['itelephony',['ITelephony',['../interface_xamarin_1_1_forms_1_1_core_1_1_i_telephony.html',1,'Xamarin::Forms::Core']]],
  ['iviewstack',['IViewStack',['../interface_xamarin_1_1_forms_1_1_core_1_1_i_view_stack.html',1,'Xamarin::Forms::Core']]]
];
